### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by shayaa99** [stellar-deprecated/paper-wallet#1]
Hello,

I am trying to buy Stellar Lumens (STR/XRP) on Changelly.com. Its asking to enter your "Memo.ID" if applicable.

Do I need a Memo.ID to transfer funds from Changelly.com to my Stellar Paper wallet? Or is the Public Key sufficient?

Thank you,
Shayaa

**Comment by bartekn** [comment]
Public Key is sufficient.
