### ISSUE TITLE
Does not work offline in Chrome

### ISSUE THREAD

**Issue by flyingalbatross** [stellar-deprecated/paper-wallet#4]
Downloaded to USB stick, unzipped and moved offline. Opened in Chrome. Version 63.0.3239.84 (Official Build) (64-bit)

Clicking 'generate' button does not produce a response or any addresses or QR codes

Same computer opened in Internet Explorer - works fine (or at least I believe so, opens and generates a code pair and QR codes)

**Comment by JellyKid** [comment]
Chrome blocks local cross origin resources.  

You can either get chrome to disable web security temporarily with  

    chrome.exe --disable-web-security --user-data-dir  

or you can run a local web server like xampp and serve the files up  
or you can edit the html and replace  

    <script type="text/javascript" src="stellar-base.min.js" ...... />  

with the actual script from the .js files

**Comment by dexterlohnes** [comment]
Hm...this is very unfortunate. Seems like it should either work out of the box or should contain a simple script to create the web server and instructions on how to use.

**Comment by bartekn** [comment]
Project no longer maintained: https://stellar.github.io/paper-wallet/
