### ISSUE TITLE
Request non minified version

### ISSUE THREAD

**Issue by JellyKid** [stellar-deprecated/paper-wallet#5]
It would be nice if we could get a non-minified version so we can see what the wallet is actually doing.

**Comment by itsrachelfish** [comment]
Yeah how are we supposed to trust this? :skull: :fire:

**Comment by kfiresmith** [comment]
Why not use this?  It's much better and you can easily inspect what it does.  It's completely offline and doesn't involve a web browser so that's an additional security bonus.
https://github.com/xaviablaza/stellar-paper-wallet

**Comment by admin4life** [comment]
It's pretty hard for the community to improve on the paper wallet generator if you don't provide a non-obfuscated version.
Really, I'm just looking for a stripped down step by step on how to generate a stellar key pair.

**Comment by minhdao** [comment]
There are SDK to use. You don't need to rely on the minified version. :)
https://www.stellar.org/developers/

**Comment by aleybovich** [comment]
You should be able to generate a paper wallet without using an sdk, especially if this repo claims to be the wallet they want the community to improve on. I woudl not recommend anyone to use this wallet unless a non-minified version is suplied. It seriously smells fishy

**Comment by bartekn** [comment]
Project no longer maintained: https://stellar.github.io/paper-wallet/
