### ISSUE TITLE
Does not state that it is for Stellar

### ISSUE THREAD

**Issue by jeffaxup** [stellar-deprecated/paper-wallet#6]
I installed this.
It appears to be the same codebase used by WalletGenerator.net.
Once loaded, it indicates that it is creating a BitCoin wallet in the top right corner.
There is nothing indicating that this is actually producing a Stellar paper wallet.
Either it needs to be much clearer to the user what it is actually creating, or perhaps this is producing a bitcoin wallet instead?
This may just be a UX problem.

**Comment by bartekn** [comment]
Are you using this URL: https://stellar.github.io/paper-wallet/ ?

If not you are not using the code in this repository.
